// Generated by   : ImageConverter Mono Online
// Generated from : plusminus.gif
// Time generated : Sun, 12 Feb 17 21:22:08 +0100  (Server timezone: CET)
// Image Size     : 6x8 pixels
// Memory usage   : 6 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype plusminus[] PROGMEM={
0x00, 0x44, 0x44, 0x5F, 0x44, 0x44, 
};
